<br />
<table>
<tr>
	<th>Title</th>
	<th>Album</th>
</tr>
<?php 
foreach($this->albums as $album ): ?>
<tr>
	<td><?php	echo $album->title; ?></td>
	<td><?php	echo $album->artist; ?></td>
	<td>
		<a href="<?php echo $this->url(array('controller'=>'index',
		'action'=>'edit', 'id'=>$album->id));?>">Edit</a>
	</td>
	<td> <a href = "<?php echo $this->url(array('controller' => 'Index', 'action' => 'delete', 'id' => $album->id)); ?>"> Delete </a>
	</td>
</tr>
<?php	endforeach; ?>

</table>
