 <!-- application/layouts/scripts/layout.phtml -->
    <?php echo $this->doctype() ?>
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <title>Zend Framework Quickstart Application</title>
      <?php echo  $this->headLink()->appendStylesheet(sprintf("%s/css/style.css", $this->baseUrl())); ?>
      <style type = "text/css">
      
     </style>
      
    </head>
    <body>
    <div id="main-container">
        <div id="header-logo">
            <b>Zend framework tutorial</b> 
        </div>
        <div id="header-navigation">
            <a href="<?php echo $this->url(
                array('controller'=>'Index', 'action' => 'add'),
                'default',
                true) ?>">Add new Album</a>
        </div>
    <br />
    		<div id="content">
        <?php echo $this->layout()->content ?>
    		</div>
    </div>
    </body>
    </html>
